services:
  app:
    image: klopez081/clarity-api
#    build: .

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: docker # specifies the resources/applications-docker.properties file
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_KEY: ${JWT_KEY}

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: noteswebapp

    ports:
      #Local port:Container Port
      - "3307:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"] # "$$" bc Container substitutes it after it starts
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s