##################
# DOCKER CONFIGS #
##################

# ENV VARIABLES ARE IN APPLICATIONS.PROPERTIES#

spring.jpa.hibernate.ddl-auto=none

#always runs SQL init scripts (schema.sql & data.sql)
spring.sql.init.mode=always

##prevents the database from being initialized before the init scripts run
#spring.jpa.defer-datasource-initialization=true

#tells spring to wait 60 seconds for a valid DB connection before failing app startup.
spring.datasource.hikari.initializationFailTimeout=60000