#################
# LOCAL CONFIGS #
#################

#allows for .env file to be read and used in program
spring.config.import=file:.env[.properties]

# ENV VARIABLES ARE IN APPLICATIONS.PROPERTIES#

spring.jpa.hibernate.ddl-auto=validate
